PYTHON = /usr/bin/python
PY_INCL = /usr/include/python2.3
LIBMAGIC = /usr/lib/libmagic.so

lib: magic.so clean_o

magic.so: py_magic.o
	ld -shared $(LIBMAGIC) py_magic.o -o magic.so

py_magic.o:
	gcc -c py_magic.c -I$(PY_INCL)

clean_o:
	rm -f *.o
clean_so:
	rm -f *.so
clean: clean_o clean_so
