# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'SLR'

_lr_signature = '\xc9\x9c*\xe5=\x87\xc5Q?\xb2h\x04\x98\x90_@'

_lr_action_items = {'VALUE':([4,],[7,]),'CDSON':([0,],[1,]),'$':([8,2,],[-1,0,]),'KEY':([1,3,7,],[4,4,-4,]),'CDSOFF':([7,5,3,6,],[-4,8,-2,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_action[(_x,_k)] = _y
del _lr_action_items

_lr_goto_items = {'assignmentList':([1,3,],[5,6,]),'submission':([0,],[2,]),'assignment':([1,3,],[3,3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_goto[(_x,_k)] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('submission',3,'p_submission','elmsubmit_submission_parser.py',54),
  ('assignmentList',1,'p_assignmentList','elmsubmit_submission_parser.py',57),
  ('assignmentList',2,'p_assignmentList','elmsubmit_submission_parser.py',58),
  ('assignment',2,'p_assignment','elmsubmit_submission_parser.py',61),
]

