## $Id$
## PERSONAL FEATURE - YOUR ALERTS

## This file is part of the CERN Document Server Software (CDSware).
## Copyright (C) 2002 CERN.
##
## The CDSware is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## The CDSware is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.  
##
## You should have received a copy of the GNU General Public License
## along with CDSware; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

##read config variables
#include "config.wml"
#include "configbis.wml"

<protect>## $Id$ </protect>
<protect>## DO NOT EDIT THIS FILE!  IT WAS AUTOMATICALLY GENERATED FROM CDSware WML SOURCES.</protect>
"""PERSONAL FEATURES - YOUR ALERTS"""

## rest of the Python code goes below

## fill config variables:
pylibdir = "<LIBDIR>/python"

try:
    import sys
    import time
    import zlib
    import urllib
    import time
    sys.path.append('%s' % pylibdir)
    from cdsware.config import *
    from cdsware.webpage import page
    from cdsware import webalert
    from cdsware.webuser import getUid
    from mod_python import apache
except ImportError, e:
    print "Error: %s" % e
    import sys
    sys.exit(1)
    
### CALLABLE INTERFACE

def display(req, p="n"):
    uid = getUid(req)	
    return page(title="Display searches",
                body=webalert.perform_display(p,uid),
                navtrail="""<a class="navtrail" href="%s/youraccount.py/display">Your Account</a>""" % weburl,
                description="CDS Personalize, Display searches",
                keywords="CDS, personalize",
                uid=uid)

def input(req, idq, name="", freq="week", notif="y", idb=0):
    uid = getUid(req)
    return page(title="Set a new alert",
                body=webalert.perform_input_alert("add", idq, name, freq, notif, idb,uid),
                navtrail="""<a class="navtrail" href="%s/youraccount.py/display">Your Account</a>""" % weburl,
                description="CDS Personalize, Set a new alert",
                keywords="CDS, personalize",
                uid=uid)

def modify(req, idq, name="", freq="week", notif="y", idb=0):
    uid = getUid(req)
    return page(title="Modify alert settings",
                body=webalert.perform_input_alert("update", idq, name, freq, notif, idb,uid),
                navtrail="""<a class="navtrail" href="%s/youraccount.py/display">Your Account</a>""" % weburl,
                description="CDS Personalize, Modify alert settings",
                keywords="CDS, personalize",
                uid=uid)

def list(req):
    uid = getUid(req)
    return page(title="Display alerts",
                body=webalert.perform_list_alerts(uid),
                navtrail="""<a class="navtrail" href="%s/youraccount.py/display">Your Account</a>""" % weburl,
                description="CDS Personalize, Display alerts",
                keywords="CDS, personalize",
                uid=uid)

def add(req, name, freq, notif, idb, bname, idq):
    uid = getUid(req)
    return page(title="Display alerts",
                body=webalert.perform_add_alert(name, freq, notif, idb, bname, idq,uid),
                navtrail="""<a class="navtrail" href="%s/youraccount.py/display">Your Account</a>""" % weburl,
                description="CDS Personalize, Display alerts",
                keywords="CDS, personalize",
                uid=uid)
def update(req, name, freq, notif, idb, bname, idq, old_idb):
    uid = getUid(req)
    return page(title="Display alerts",
                body=webalert.perform_update_alert(name, freq, notif, idb, bname, idq, old_idb,uid),
                navtrail="""<a class="navtrail" href="%s/youraccount.py/display">Your Account</a>""" % weburl,
                description="CDS Personalize, Display alerts",
                keywords="CDS, personalize",
                uid=uid)

def remove(req, name, idu, idq, idb):
    uid = getUid(req) 
    return page(title="Display alerts",
                body=webalert.perform_remove_alert(name, idu, idq, idb, uid),
                navtrail="""<a class="navtrail" href="%s/youraccount.py/display">Your Account</a>""" % weburl,
                description="CDS Personalize, Display alerts",
                keywords="CDS, personalize",
                uid=uid)


