..  This file is part of Invenio
    Copyright (C) 2014, 2015 CERN.

    Invenio is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License as
    published by the Free Software Foundation; either version 2 of the
    License, or (at your option) any later version.

    Invenio is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Invenio; if not, write to the Free Software Foundation, Inc.,
    59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

Getting Started
===============

This part of the documentation, which is mostly prose, begins with some
background information about Invenio, then focuses on step-by-step
instructions for customization of Invenio.

.. toctree::
   :maxdepth: 2

   getting-started/index

.. _developer-guide:

Developer's Guide
=================

The Invenio Developers' corner. Before diving into the source, make sure you
don't miss our user-level and admin-level documentation as well. And now, back
to the source, and happy hacking!

.. toctree::
   :maxdepth: 2

   developers/index

.. _api-reference:

Admins's Guide
==============

.. toctree::

   admin/index

API Reference
=============

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

Community
=========

.. toctree::
   :maxdepth: 2

   community/index

.. _additional-notes:

Additional Notes
================

Design notes, legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 1

   deprecationpolicy
   upgrading
   license
