User's Guide
------------

This part of the documentation, which is mostly prose, begins with some
background information about Invenio, then focuses on step-by-step
instructions for customization of Invenio.

.. toctree::
   :maxdepth: 1

   features
   demo
   modules

Admin's Guide
-------------

.. toctree::
   :maxdepth: 1

   common-concepts
   pluggable-objects

Developer's Guide
-----------------

The Invenio Developers' corner. Before diving into the source, make sure you
don't miss our user-level and admin-level documentation as well. And now, back
to the source, and happy hacking!

.. toctree::
   :maxdepth: 1

   developers/introduction
   developers/extensions
   developers/modules
   developers/templates
   developers/git-workflow

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

Additional Notes
----------------

Design notes, legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 2

   design
   extensiondev
   styleguide
   upgrading
   changelog
   license
