Getting Started
===============

This part of the documentation, which is mostly prose, begins with some
background information about Invenio, then focuses on step-by-step
instructions for customization of Invenio.

.. toctree::
   :maxdepth: 2

   getting-started/index

.. _developer-guide:

Developer's Guide
=================

The Invenio Developers' corner. Before diving into the source, make sure you
don't miss our user-level and admin-level documentation as well. And now, back
to the source, and happy hacking!

.. toctree::
   :maxdepth: 2

   developers/index

.. _api-reference:

API Reference
=============

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

.. _additional-notes:

Additional Notes
================

Design notes, legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 1

   upgrading
   license
