START::DEFP()---<record>
001::REPL(EOL,)---<controlfield tag="001"><:SN::SN:></controlfield>
041a::REPL(EOL,)::MINLW(82)---<datafield tag="041" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_LANG::DEMOTHE_LANG::IF(Select:,,ORIG):></subfield></datafield>
088::REPL(EOL,)::MINLW(82)---<datafield tag="088" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_REP*::DEMOTHE_REP:></subfield></datafield>
100::REP(EOL,)::RANGE(1,1)::MINLW(82)---<datafield tag="100" ind1=" " ind2=" "><:AUTHOR_FULLNAME*::AUTHOR_FULLNAME::IF(#None#, ,<subfield code="a">):><:AUTHOR_FULLNAME*::AUTHOR_FULLNAME::IF(#None#, ,ORIG):><:AUTHOR_FULLNAME*::AUTHOR_FULLNAME::IF(#None#, ,</subfield>):><:AUTHOR_ID*::AUTHOR_ID::IF(#None#, ,<subfield code="0">):><:AUTHOR_ID*::AUTHOR_ID::IF(#None#, ,ORIG):><:AUTHOR_ID*::AUTHOR_ID::IF(#None#, ,</subfield>):><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION::IF(#None#, ,<subfield code="g">):><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION::IF(#None#, ,ORIG):><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION::IF(#None#, ,</subfield>):><:AUTHOR_AFFILIATION*::AUTHOR_AFFILIATION::IF(#None#, ,<subfield code="u">):><:AUTHOR_AFFILIATION*::AUTHOR_AFFILIATION::IF(#None#, ,ORIG):><:AUTHOR_AFFILIATION*::AUTHOR_AFFILIATION::IF(#None#, ,</subfield>):><:AUTHOR_EMAIL*::AUTHOR_EMAIL::IF(#None#, ,<subfield code="m">):><:AUTHOR_EMAIL*::AUTHOR_EMAIL::IF(#None#, ,ORIG):><:AUTHOR_EMAIL*::AUTHOR_EMAIL::IF(#None#, ,</subfield>):></datafield>
245a::REPL(EOL,)::MINLW(82)---<datafield tag="245" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_TITLE::DEMOTHE_TITLE:></subfield><:DEMOTHE_SUBTTL::DEMOTHE_SUBTTL::IF(,,<subfield code="b">):><:DEMOTHE_SUBTTL::DEMOTHE_SUBTTL:><:DEMOTHE_SUBTTL::DEMOTHE_SUBTTL::IF(,,</subfield>):></datafield>
300::REPL(EOL,)::MINLW(82)---<datafield tag="300" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_NUMP::DEMOTHE_NUMP:></subfield></datafield>
520a::REP(EOL,)::MINLW(82)---<datafield tag="520" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_ABS::DEMOTHE_ABS:></subfield></datafield>
700a::REP(EOL,)::RANGE(2,1999)::MINLW(82)---<datafield tag="700" ind1=" " ind2=" "><:AUTHOR_FULLNAME*::AUTHOR_FULLNAME::IF(#None#, ,<subfield code="a">):><:AUTHOR_FULLNAME*::AUTHOR_FULLNAME::IF(#None#, ,ORIG):><:AUTHOR_FULLNAME*::AUTHOR_FULLNAME::IF(#None#, ,</subfield>):><:AUTHOR_ID*::AUTHOR_ID::IF(#None#, ,<subfield code="0">):><:AUTHOR_ID*::AUTHOR_ID::IF(#None#, ,ORIG):><:AUTHOR_ID*::AUTHOR_ID::IF(#None#, ,</subfield>):><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION::IF(#None#, ,<subfield code="g">):><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION::IF(#None#, ,ORIG):><:AUTHOR_CONTRIBUTION*::AUTHOR_CONTRIBUTION::IF(#None#, ,</subfield>):><:AUTHOR_AFFILIATION*::AUTHOR_AFFILIATION::IF(#None#, ,<subfield code="u">):><:AUTHOR_AFFILIATION*::AUTHOR_AFFILIATION::IF(#None#, ,ORIG):><:AUTHOR_AFFILIATION*::AUTHOR_AFFILIATION::IF(#None#, ,</subfield>):><:AUTHOR_EMAIL*::AUTHOR_EMAIL::IF(#None#, ,<subfield code="m">):><:AUTHOR_EMAIL*::AUTHOR_EMAIL::IF(#None#, ,ORIG):><:AUTHOR_EMAIL*::AUTHOR_EMAIL::IF(#None#, ,</subfield>):></datafield>
700a::REP(EOL,)::MINLW(116)---<datafield tag="700" ind1=" " ind2=" "><subfield code="a"><:DEMOTHE_SUPERV*::DEMOTHE_SUPERV:></subfield><subfield code="e">dir.</subfield></datafield>
END::DEFP()---</record>
