## $Id$
SN---<:SN:>
SuE---<:SuE:>
DEMOTXT_RN---<:DEMOTXT_RN:>
DEMOTXT_LANG---<:DEMOTXT_LANG:>
DEMOTXT_REP---<:DEMOTXT_REP:>
DEMOTXT_AU---<:DEMOTXT_AU:>
DEMOTXT_TITLE---<:DEMOTXT_TITLE:>
DEMOTXT_DATE---<:dd:>/<:mm:>/<:year:>
DEMOTXT_NUMP---<:DEMOTXT_NUMP:>
DEMOTXT_ABS---<:DEMOTXT_ABS:>
DEMOTXT_FILE_RENAMED---<:DEMOTXT_FILE_RENAMED:>
DEMOTXT_NOTE---<:DEMOTXT_NOTE:>
DEMOTXT_KW---<:DEMOTXT_KW:>
comboDEMOTXT---<:comboDEMOTXT:>
